@TM:1547799987
@N:  :"":0:0:0:-1|premap output is up to date. No run necessary.
@N:  :"":0:0:0:-1|fpga_mapper output is up to date. No run necessary.
@TM:1547799986
@N:  :"":0:0:0:-1|Running in 64-bit mode
@N:  :"":0:0:0:-1|: Running Verilog Compiler in System Verilog mode
@N:  :"":0:0:0:-1|: Running Verilog Compiler in Multiple File Compilation Unit mode
@TM:1547799298
@N: BN225 :"":0:0:0:-1|Writing default property annotation file C:\ue\synplify\rev_1\proj_1.sap.
@TM:1547799300
@N: FX164 :"":0:0:0:-1|The option to pack registers in the IOB has not been specified. Please set syn_useioff attribute.  
@TM:1547799298
@W: FX474 :"":0:0:0:-1|User-specified initial value defined for some sequential elements which can prevent optimum synthesis results from being achieved. 
@TM:1547799300
@N: MF248 :"":0:0:0:-1|Running in 64-bit mode.
@TM:1547799298
@N: MF248 :"":0:0:0:-1|Running in 64-bit mode.
@TM:1547799300
@N: MF666 :"":0:0:0:-1|Clock conversion enabled 
@TM:1547799298
@N: MF666 :"":0:0:0:-1|Clock conversion enabled 
@TM:1547799300
@N: MT206 :"":0:0:0:-1|Auto Constrain mode is enabled
@N: MT320 :"":0:0:0:-1|Timing report estimates place and route data. Please look at the place and route timing report for final timing.
@N: MT322 :"":0:0:0:-1|Clock constraints cover only FF-to-FF paths associated with the clock.
@W: MT420 :"":0:0:0:-1|Found inferred clock trigger_active|clk with period 0.76ns. Please declare a user-defined clock on object "p:clk"
@TM:1547799986
@N: CG364 :"C:\ue\synplify\trigger_active.v":28:7:28:20|Synthesizing module trigger_active
@TM:1547799298
@W: MT529 :"c:\ue\synplify\trigger_active.v":68:1:68:6|M
