clk
reset
iv_pkt_length
iv_remain_pkt_length
iv_pic_pkt_cnt
iv_image_size
iv_payload_size
i_resend_valid
i_resend_unavail
iv_resend_packet_id_first
iv_resend_packet_id_last
o_addr_calc_done
o_resend_need_info
ov_resend_invalid_length
ov_resend_require_length
ov_resend_chunk_invalid_length
ov_resend_chunk_require_length
